phidgets:
  floor_force_sensor:
    bridge_gain: 8
    channel: 0
    channel_class: VoltageRatioInput
    data_interval: 250
    device_serial_number: 514010
    hub_port: 5
    label: LOAD CELL
    voltage_ratio_change_trigger: 1.0e-05
  head_bar_switch:
    channel: 0
    channel_class: DigitalInput
    device_serial_number: 514010
    hub_port: 4
    label: SWITCH 2
  latch_motors:
    acceleration: 100000
    current_limit: 0.5
    holding_current_limit: 0.5
    velocity_limit: 100000
  left_head_latch_home_switch:
    channel: 0
    channel_class: DigitalInput
    device_serial_number: 514010
    hub_port: 3
    label: SWITCH 1
  left_head_latch_motor:
    channel: 0
    channel_class: Stepper
    close_position: 1150
    device_serial_number: 514010
    home_velocity: -400
    hub_port: 2
    label: MOTOR 1
    release_position: 10
  release_switch:
    channel: 0
    channel_class: DigitalInput
    device_serial_number: 530381
    hub_port: 0
    label: SWITCH 3
  right_head_latch_home_switch:
    channel: 0
    channel_class: DigitalInput
    device_serial_number: 514010
    hub_port: 1
    label: SWITCH 0
  right_head_latch_motor:
    channel: 0
    channel_class: Stepper
    close_position: -1150
    device_serial_number: 514010
    home_velocity: 400
    hub_port: 0
    label: MOTOR 0
    release_position: -10
